# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.


development:
  secret_key_base: ebfe351b57baa1d55722d4a1d70a8dd1638706226dddfbe72d15cffeedbfda86c7e37619824ce3830fe441d688e7e240c567b2dc774b24b592b803ea2b965960
  sendgrid_apy_key: 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
test:
  secret_key_base: 59c3ff8bf6555e55edf70fd1134547920b945034d59474bb711b68e21caa39742450fe045598aba99d196bae8e47a70fd43ca8516a08c9e33c39944098cb050b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
